group: default
dataset: CIFAR10
model: dummy
criterion: cross-entropy
optimizer: adam
seed: 1
num-workers: 4
batch-size: 32
learning-rate: 0.1
momentum: 0.9
weight-decay: 0.0005
max-epochs: 2
warmup-epochs: 5

# SBATCH params
nodes: 1
gpus-per-node: 4
time: 00:20:00
