# TODO: Add more options if required

dataset: CIFAR10
model: alexnet
case: pre-step-local
seed: 1
num-workers: 4
batch-size: 128
learning-rate: 0.1
momentum: 0.9
weight-decay: 0.0005
num-epochs: 50
warmup-epochs: 5
