group: default
dataset: CIFAR10
model: dummy
case: pre_step_local
criterion: cross-entropy
optimizer: adam
seed: 1
num-workers: 4
batch-size: 32
learning-rate: 0.1
momentum: 0.9
weight-decay: 0.0005
max-epochs: 2
warmup-epochs: 5
